language: cpp
sudo: true

matrix:
  include:

    - os: linux
      compiler: gcc
      env: SOURCES=ubuntu-toolchain-r-test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
             # compilers
            - g++
            - cmake
            - libqt4-dev
            - qt4-dev-tools
            - pyqt4-dev-tools
            - libqt4-opengl-dev
            - libeigen3-dev
            - libwxgtk3.0-dev

install:
  - pip install --user virtualenv
  # get newest cmake
  - curl https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz | tar xvz
  - export PATH=$PWD/cmake-3.5.2-Linux-x86_64/bin:$PATH
  - export LD_LIBARY_PATH=$PWD/cmake-3.5.2-Linux-x86_64/lib:$LD_LIBRARY_PATH
  # get the newest openbabel manually (preinstalled packages are old !)
  - export GIT_SSL_NO_VERIFY=true
  #- git clone git@github.com:openbabel/openbabel.git $PWD/openbabel
  - git clone https://github.com/miroi/openbabel.git $PWD/openbabel
  - cd $PWD/openbabel
  - pwd
  - ls -lt
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - make -j4
  - ls -lt bin/
  - ls -lt lib/
  - export PATH=$PWD/openbabel/build/bin:$PATH
  - export LD_LIBARY_PATH=$PWD/openbabel/build/lib:$LD_LIBRARY_PATH
  - cd ../..
  - virtualenv venv
  - source venv/bin/activate

before_script:
  - pwd
  - cd avogadro
  - ls -lt
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - ls -lt

script:
  - uname -a

# turn off email notifications
notifications:
  email: false
