language: cpp
dist: trusty
sudo: false

before_script:
  - pwd
  - uname -a
  - lscpu
  - df -h
  - free -m -g
  - cmake --version
  - let "N_PROC=$(cat /proc/cpuinfo | grep processor | wc -l)"
  - echo "Number of processors/jobs for the serial build step is $N_PROC"

script:
  - cd avogadro
  - ls -lt
  - mkdir build
  - cd build
  - cmake ..
  - make -j $N_PROC
  - ls -lt

# turn off email notifications
notifications:
  email: false
