language: cpp
dist: trusty
sudo: false

install:
   #- sudo apt-get install qtchooser # is already installed
   #- sudo apt-get install qttools5-dev-tools
   - sudo apt-get install qt4-linguist-tools
   - sudo apt install qt4-dev-tools

before_script:
  - pwd
  - uname -a
  - lscpu
  - df -h
  - free -m -g
  - cmake --version
  - let "N_PROC=$(cat /proc/cpuinfo | grep processor | wc -l)"
  - echo "Number of processors/jobs for the serial build step is $N_PROC"
  # verify Qt4 and related stuff is installed
  - qmake --version
  - lupdate-qt4 -version
  - lrelease-qt4 -version
  - which lconvert
  - /usr/bin/lconvert -h

script:
  - cd avogadro
  - du -h -s .
  - ls -lt
  - mkdir build
  - cd build
  - cmake ..
  - make -j $N_PROC VERBOSE=1
  - ls -lt

# turn off email notifications
notifications:
  email: false
