language: cpp
sudo: true

matrix:
  include:

    - os: linux
      compiler: gcc
      env: SOURCES=ubuntu-toolchain-r-test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
             # compilers
            - g++
            - cmake
            - libqt4-dev
            - libopenbabel4
            - libeigen3-dev

install:
  - virtualenv venv
  - source venv/bin/activate
  - pip install pep8 pytest

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j4
  - ls -lt

# turn off email notifications
notifications:
  email: false
