language: cpp
sudo: true

matrix:
  include:

    - os: linux
      compiler: gcc
      env: SOURCES=ubuntu-toolchain-r-test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
             # compilers
            - g++
            #- cmake
            - libqt4-dev
            - libeigen3-dev

install:
  - pip install --user virtualenv
  # get newest cmake
  - curl https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz | tar xvz
  - export PATH=$PWD/cmake-3.5.2-Linux-x86_64/bin:$PATH
  - export LD_LIBARY_PATH=$PWD//cmake-3.5.2-Linux-x86_64/lib:$LD_LIBRARY_PATH
  # get the newest openbabel (packages are old !)
  - export GIT_SSL_NO_VERIFY=true
  - git clone git@github.com:openbabel/openbabel.git
  - cd $PWD/openbabel
  - mkdir build
  - cd build
  - cmake ..
  - make -j 2
  - ls -lt
  - export PATH=$PWD/openbabel/build:$PATH
  - virtualenv venv
  - source venv/bin/activate

before_script:
  - which cmake
  - ls $PWD/cmake-3.5.2-Linux-x86_64/bin/.
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j4
  - ls -lt

# turn off email notifications
notifications:
  email: false
