language: cpp
sudo: true

matrix:
  include:

    - os: linux
      compiler: gcc
      env: SOURCES=ubuntu-toolchain-r-test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
             # compilers
            - g++
            #- cmake
            - libqt4-dev
            - libopenbabel4
            - libeigen3-dev

install:
  - pip install --user virtualenv
  - curl https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz | tar xvz
  - export PATH=~/cmake-3.5.2-Linux-x86_64/bin:$PATH
  - export LD_LIBARY_PATH=~/cmake-3.5.2-Linux-x86_64/lib:$LD_LIBRARY_PATH
  - virtualenv venv
  - source venv/bin/activate
  #- pip install pep8 pytest

before_script:
  - which cmake
  - ls ~/cmake-3.5.2-Linux-x86_64/bin/.
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j4
  - ls -lt

# turn off email notifications
notifications:
  email: false
